# Generated by Django 6.0.2 on 2026-03-05 19:11

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_imgs')),
                ('caption', models.TextField()),
                ('created_time', models.DateTimeField(default=datetime.datetime(2026, 3, 5, 19, 11, 44, 903365))),
                ('likes_n', models.IntegerField(default=0)),
            ],
        ),
    ]
